version: '3'
services:
    backend:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        hostname: 'backend'
        ports: [
            3306:3306
        ]
        environment: {
            MYSQL_ROOT_PASSWORD: password
        }
        volumes:
            - ./data/backend:/var/lib/mysql:rw
    middleware-API:
        image: lslio/nginx-php-fpm
        restart: always
        hostname: 'middleware-API'
        ports: [
            8080:80
        ]
        volumes:
            - ./data/middleware-API:/www
    frontend:
        image: nginx
        restart: always
        hostname: 'frontend'        
        ports: [
            8000:80
        ]
        volumes:
            - ./data/frontend:/usr/share/nginx/html